version: "2.2"
services:
  api:
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"